/** Generated by src/scripts/genIcons.ts */

import React from 'react';
import dataJSON from '@/output/cloud-storage.ast';
import { SVGNode, SVGRoot } from '@/scripts/translate';

const CloudStorage = () => {

    const astJson = dataJSON as unknown as SVGRoot;

    const renderNode = (node: SVGNode): React.ReactNode => {
        const { type, attributes, children } = node;
        
        const props = {
            ...attributes,
            key: Math.random().toString(36).substr(2, 9)
        };

        if (children) {
            return React.createElement(
                type,
                props,
                children.map(child => renderNode(child))
            );
        }

        return React.createElement(type, props);
    };

    if (!astJson) {
        return null;
    }

    return (
        <>
            {renderNode(astJson)}
        </>
    );
}

export default CloudStorage;
