import path from 'path';
import ejs from 'ejs';
import { readdirSync, readFileSync, writeFileSync } from 'fs';

/**
 * 自动生成 icons 目录下所有组件的导出文件 index.tsx
 */
const main = () => {
    const iconsDir = path.join(__dirname, '../icons');
    const files = readdirSync(iconsDir);

    // 文件头注释，提示自动生成
    let resContent = '// This file is auto-generated by generateIndex.tsx, do not edit it manually.\n\n';

    // 遍历 icons 目录下所有 tsx 文件，生成导出语句
    files.forEach((file, idx) => {
        const template = readFileSync(path.join(__dirname, '../templates/index.tsx.ejs'), 'utf8');
        const data = { name: file.replace('.tsx', '') };
        const content = ejs.render(template, data);

        console.log(`${idx + 1}/${files.length} 生成导出:`, content.trim());
        resContent += content + '\n';
    });

    // 写入 index.tsx
    writeFileSync(path.join(__dirname, '../index.tsx'), resContent);
};

main();
