import path from 'path';
import ejs from 'ejs';
import { readdirSync, readFileSync, writeFileSync, mkdirSync, existsSync } from 'fs';

const main = () => {
    const iconsDir = path.join(__dirname, 'icons');
    const files = readdirSync(iconsDir);
    const total = files.length;
    let count = 0;

    let resContent = '// This file is auto-generated by generateIndex.tsx, do not edit it manually.\n\n';

    for (const file of files) {
        count++;
        console.log(`${count}/${total} ${file}`);

        // // 读取模板文件
        const template = readFileSync(path.join(__dirname, 'export.ejs'), 'utf8');
        // // 渲染数据
        const data = { name: file.replace('.tsx', '') };
        const content = ejs.render(template, data);

        console.log('生成的内容:', content);
        resContent += content + '\n';
    }

    writeFileSync(path.join(__dirname, 'index.tsx'), resContent);
}

main()
